from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from check_commit_attribution import (  # noqa: E402
    check_text,
    find_forbidden_lines,
    iter_commit_records,
    main,
)


class CommitAttributionTests(unittest.TestCase):
    def test_clean_conventional_message_passes(self):
        text = "ci: forbid agent co-authors\n\nDo not add those trailers.\n"
        self.assertEqual(find_forbidden_lines(text), [])
        self.assertEqual(check_text("commit message", text), [])

    def test_co_authored_by_is_rejected(self):
        text = "ci: something\n\nCo-authored-by: Cursor <cursoragent@cursor.com>\n"
        hits = find_forbidden_lines(text)
        self.assertEqual(len(hits), 1)
        self.assertIn("Co-authored-by", hits[0])

    def test_co_committed_by_is_rejected_case_insensitive(self):
        text = "fix: bug\n\nCO-COMMITTED-BY: Agent <noreply@anthropic.com>\n"
        self.assertTrue(find_forbidden_lines(text))

    def test_hash_comment_lines_are_ignored(self):
        text = "chore: tidy\n# Co-authored-by: ignored because git comments this out\n"
        self.assertEqual(find_forbidden_lines(text), [])

    def test_agent_email_without_trailer_is_rejected(self):
        text = "feat: demo\n\nGenerated by cursoragent@cursor.com\n"
        self.assertTrue(find_forbidden_lines(text))

    def test_iter_commit_records_splits_on_rs(self):
        log = (
            "abc123\nSoura <you@example.com>\nSoura <you@example.com>\n"
            "feat: one\n\x1e"
            "def456\nSoura <you@example.com>\nSoura <you@example.com>\n"
            "fix: two\n"
        )
        records = list(iter_commit_records(log))
        self.assertEqual(len(records), 2)
        self.assertEqual(records[0][0], "abc123")
        self.assertIn("feat: one", records[0][1])

    def test_main_rejects_message_file(self):
        with tempfile.NamedTemporaryFile(
            "w",
            suffix=".txt",
            delete=False,
            encoding="utf-8",
        ) as handle:
            handle.write("chore: test\n\nCo-authored-by: Copilot <copilot@github.com>\n")
            path = handle.name
        try:
            self.assertEqual(main([path]), 1)
        finally:
            Path(path).unlink(missing_ok=True)


if __name__ == "__main__":
    unittest.main()
